#!/bin/sh
echo "Generating env.json file from environment variables..."
cat <<EOF > env.json
{
  "FIREBASE_API_KEY": "${FIREBASE_API_KEY}",
  "FIREBASE_AUTH_DOMAIN": "${FIREBASE_AUTH_DOMAIN}",
  "FIREBASE_PROJECT_ID": "${FIREBASE_PROJECT_ID}",
  "FIREBASE_STORAGE_BUCKET": "${FIREBASE_STORAGE_BUCKET}",
  "FIREBASE_MESSAGING_SENDER_ID": "${FIREBASE_MESSAGING_SENDER_ID}",
  "FIREBASE_APP_ID": "${FIREBASE_APP_ID}",
  "FIREBASE_MEASUREMENT_ID": "${FIREBASE_MEASUREMENT_ID}"
}
EOF
echo "env.json file generated successfully!"
